

trigger:
- main

pool:
  name: DevProdQApool


steps:

- task: TerraformTask@5

  displayName: init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
    backendServiceArm: 'EnvironmentDevProdQA'
    backendAzureRmStorageAccountName: 'storageproduction9838'
    backendAzureRmContainerName: 'container9838'
    backendAzureRmKey: '1234'
- task: TerraformTask@5
  displayName: plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
    environmentServiceNameAzureRM: 'EnvironmentDevProdQA'
- task: TerraformTask@5
  displayName: apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Prod'
    environmentServiceNameAzureRM: 'EnvironmentDevProdQA'