

trigger:
- main

pool:
  name: DevProdQApool


steps:

- task: TerraformTask@5
  displayName: init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'EnvironmentDevProdQA'
    backendAzureRmStorageAccountName: 'storageproduction9838'
    backendAzureRmContainerName: 'container9838'
    backendAzureRmKey: '1234'